# Generated by Django 3.0 on 2019-12-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='arrival_date',
            new_name='return_date',
        ),
    ]
