# Generated by Django 3.0 on 2019-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20191207_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='return_date',
            field=models.DateField(),
        ),
    ]
